# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{convert_office}
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amar Daxini", "Stuart Owen"]
  s.date = %q{2012-09-26}
  s.description = %q{}
  s.email = %q{stuart.owen@manchester.ac.uk}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "convert_office.gemspec",
    "install.rb",
    "lib/convert_office.rb",
    "lib/convert_office_config.rb",
    "lib/generator/convert_office_nailgun",
    "lib/java/jar/convert_office.jar",
    "lib/tasks/convert_office_tasks.rake",
    "rails/init.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/stuzart/convert_office}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

